thijsvanloef/palworld-server-docker

- docker-compose.yml
> Fix server port typo in docker-compose.yml

- Dockerfile
closes #17 
Add pgrep healthcheck to the image
> add healthcheck

- Dockerfile
- README.md
- docker-compose.yml
- scripts/start.sh
https://github.com/thijsvanloef/palworld-server-docker/issues/29#issuecomment-1902727593
> make port and players optional

- Dockerfile
- README.md
- docker-compose.yml
- scripts/start.sh
> Enable RCON 

- README.md
full path inside the container needs to have LinuxServer included.
> update README with LinuxServer for the path of PalWorldSettings.ini

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/pull_request_template.md
- .github/workflows/linting.yml
- .markdownlint.jsonc
- README.md
Enable linting on Markdown files
Automated using github actions
1. Open PR
2. Test if Automated Linting runs
> Add Automated Markdownlint

- README.md
As discussed in Issue #87 I've added a link to the website I found
> Link to PalWorldSettings Explanations

- README.md
> Fix: Typo in documentation

- README.md
- scripts/backup.sh
* To save the server before running backup
* Added same check for saving that's was added in #98 
1. Run backup command
> Backup save

- scripts/start.sh
Reverts thijsvanloef/palworld-server-docker#124
> Revert "updating STARTCOMMAND to array with += syntax and allowing spaces in …"

- .github/workflows/linting.yml
- scripts/start.sh
Have stricter shellcheck on the repo
Replace shell-linter with shellcheck 
set minimum severity from error to warning
Open a PR, check that the shellcheck runs
> replace shellcheck

- README.md
I really like shields.io, but clicking them shouldn't lead you to the shield, it should lead you to the relvenant information
- Add relevant hyperlinks to readme shields
> Add hyperlinks to readme shields

- README.md
- docs/zh-CN/README.md
- Added Simplified Chinese translation of README.md
> docs: Add Simplified Chinese translation of README.md

- docs/zh-CN/README.md
> docs: small translation fix

- .github/workflows/docker-hub.yml
- .github/workflows/linting.yml
- .github/workflows/release.yml
Keeping things clean, simplistic, and following a standard
- Use latest github-actions, primarily to get on node20
- Remove `with: lint` from dockerfile linting, `lint` isn't a valid option
- Add & standardize names to individual steps
- Specify the run-name in the Linting workflow, to better know at a glance which pull requests the workflow run was for
> Standardize & Cleanup workflows

- docs/kr/README.md
* Korean version of README.md There are parts of the README.md that are not translated into Korean and remain in English.
* Performed additional translations.
1.
> Translate more untranslated content

- charts/palworld/templates/services.yaml
* The service annotations were wrong pointed to server config annotations
> - Fixed wrong property in the service annotation;

- docs/zh-CN/README.md
Supplement and modify the Chinese `README.md` to make its documentation more standardized and formatted.
> Update README.md for zh_CN

- docs/zh-CN/README.md
Fill in missing document content.
> Update: add zh_CN translations with version `0.19.0`.

- charts/palworld/Chart.yaml
Our helm chart should be good to go to put on artifact hub, https://artifacthub.io/
- Add artifact-hub specific annotations to the Helm Chart
> Add artifact-hub annotations

- docs/kr/README.md
* [!Tip] Apply highlighting of syntax
* Changed because `[!Tip]` and `[!Important]` were not highlighted when translating to Korean. 
* [v] I have performed a self-review of my code
* [v] I've added documentation about this change to the README.
* [v] I've not introduced breaking changes.
> Fix kr README.md

- docs/kr/README.md
- docs/zh-CN/README.md
I'm sorry, I made a mistake in my previous changes and forgot to save. :(
> Incorrect link fix

- README.md
- docs/kr/README.md
* Update README to list macOS as supported platform.
* Changed README for English and Korean, still requires Chinese translation but I don't know any single Chines characters.
> Updated README to list macOS as supported platform.

- docs/zh-CN/README.md
* [✔] I have performed a self-review of my code
* [✔] I've added documentation about this change to the README.
* [✔] I've not introduced breaking changes.
> Update: Add Apple Silicon docs.

- README.md
Include documentation for manual backup restoration for those who are not familiar with the process.
> add manully restore document

- docs/zh-CN/README.md
add zh_CN translations for docker setting
> add zh_CN translations for docker setting

- .github/FUNDING.yml
- .github/dependabot.yml
- .github/workflows/docker-hub.yml
- .github/workflows/linting.yml
- .github/workflows/release.yml
- .github/workflows/sponsors.yml
- .yamllint.yml
- charts/cr.yaml
- charts/palworld/Chart.yaml
- charts/palworld/values.yaml
- docker-compose.yml
- k8s/configmap.yaml
- k8s/deployment.yaml
- k8s/examples/cronjob-reboot/cm.yaml
- k8s/examples/cronjob-reboot/cronjob.yaml
- k8s/examples/cronjob-reboot/role.yaml
- k8s/examples/cronjob-reboot/rolebinding.yaml
- k8s/examples/cronjob-reboot/serviceaccount.yaml
- k8s/pvc.yaml
- k8s/secret.yaml
- k8s/service.yaml
There has been some debate on how to format yaml files, this pr make sure that all yaml files meet the required standards
.yamllint.yml forced everyone to use the same rules.
Open PR, check if yamllint runs
> Enable yamllint on whole repo

- docs/zh-CN/README.md
> Update zh-CN translation

- README.md
Issue #323 asked for a better explanation on how to convert server settings to environment variables
I've added explanations of typical conversions to the README.md as well as linking a wiki that lists all possible server settings
> Introduce more documentation

- README.md
Make sure people do not overlook the option to run this image on ARM64 based hosts
> Update readme to include ARM warning

- docs/zh-CN/README.md
> Update zh-cn read.md

- docusaurus/docusaurus.config.js
- docusaurus/package-lock.json
- docusaurus/package.json
I want to know what pages are used most frequently
* 
1.
> Fix docusaurus "edit this page" links and add anonymised analytics 

- docusaurus/docusaurus.config.js
> add docker hub link to docusaurus

- docusaurus/docusaurus.config.js
> add algolia search

- docusaurus/docusaurus.config.js
- docusaurus/i18n/nl/code.json
- docusaurus/i18n/nl/docusaurus-plugin-content-docs/current.json
- docusaurus/i18n/nl/docusaurus-plugin-content-docs/current/advanced/_category_.json
- docusaurus/i18n/nl/docusaurus-plugin-content-docs/current/advanced/kubernetes.md
- docusaurus/i18n/nl/docusaurus-plugin-content-docs/current/advanced/palworld-directory.md
- docusaurus/i18n/nl/docusaurus-plugin-content-docs/current/getting-started/_category_.json
- docusaurus/i18n/nl/docusaurus-plugin-content-docs/current/getting-started/configuration/_category_.json
- docusaurus/i18n/nl/docusaurus-plugin-content-docs/current/getting-started/configuration/game-settings.md
- docusaurus/i18n/nl/docusaurus-plugin-content-docs/current/getting-started/configuration/server-commands.md
- docusaurus/i18n/nl/docusaurus-plugin-content-docs/current/getting-started/configuration/server-settings.md
- docusaurus/i18n/nl/docusaurus-plugin-content-docs/current/getting-started/quick-setup.md
- docusaurus/i18n/nl/docusaurus-plugin-content-docs/current/guides/_category_.json
- docusaurus/i18n/nl/docusaurus-plugin-content-docs/current/guides/automatic-reboots.md
- docusaurus/i18n/nl/docusaurus-plugin-content-docs/current/guides/automatic-updates.md
- docusaurus/i18n/nl/docusaurus-plugin-content-docs/current/guides/backup/_category_.json
- docusaurus/i18n/nl/docusaurus-plugin-content-docs/current/guides/backup/automated-backup.md
- docusaurus/i18n/nl/docusaurus-plugin-content-docs/current/guides/backup/creating-backup.md
- docusaurus/i18n/nl/docusaurus-plugin-content-docs/current/guides/backup/restoring-backup.md
- docusaurus/i18n/nl/docusaurus-plugin-content-docs/current/guides/discord/_category_.json
- docusaurus/i18n/nl/docusaurus-plugin-content-docs/current/guides/discord/discord-webhooks.md
- docusaurus/i18n/nl/docusaurus-plugin-content-docs/current/known-issues/known-issues.md
- docusaurus/i18n/nl/docusaurus-plugin-content-docs/current/versions/versions.md
- docusaurus/i18n/nl/docusaurus-theme-classic/footer.json
- docusaurus/i18n/nl/docusaurus-theme-classic/navbar.json
> add dutch docs

- docusaurus/i18n/de/docusaurus-plugin-content-docs/current/getting-started/configuration/game-settings.md
- docusaurus/i18n/de/docusaurus-plugin-content-docs/current/getting-started/quick-setup.md
- docusaurus/i18n/de/docusaurus-plugin-content-docs/current/guides/pinning-game-version.md
- docusaurus/i18n/de/docusaurus-plugin-content-docs/current/guides/running-without-root.md
* updated german translation to the changes since `bb02493` (`git diff bb02493 main docusaurus`)
* added new translations for pinning-game-version and running-without-root
* 
1.  Navigate to the docusaurus folder
2. Run: `npm start -- --locale de`
> German docu update

- scripts/auto_reboot.sh
- scripts/helper_functions.sh
- scripts/update.sh
* Added broadcast function and check if message is ASCII as mentioned in #400 
* Code from #392 
* Added in checking for ASCII so users trying to use none ASCII. Staging for #401 and to give users more insignt for issues like #253
1. Test the broadcast in game by scheduling a cron reboot
2. Verify the message as underscores in game
> Create broadcast function

- .github/workflows/linting.yml
- .github/workflows/security.yml
Run linting and sec scan on main
* 
1.
> cleanup workflows

- docusaurus/docs/guides/automatic-server-stopping.md
Add documentation on how to start/stop the container when no players are connected
* 
1.
> add automatic start/stop documentation

- docusaurus/docs/guides/rcon/_category_.json
- docusaurus/docs/guides/rcon/rcon-wrapper.md
Add https://github.com/thijsvanloef/palworld-server-docker/issues/165 to official documentation
* 
1.
> add rcon-wrapper docs

- README.md
- docusaurus/docs/guides/pinning-game-version.md
- docusaurus/docs/guides/rcon/rcon-wrapper.md
Fixes #469
Add new Manifest ID to docs
* 
1.
> update manifest id, fix typo

- docs/kr/README.md
Updated to follow current en README.md
* To inform users the most current information about the repository
* 
1.
> Update ko-kr README.md

- docs/kr/README.md
- docs/zh-CN/README.md
Move everything to docusaurus.
* 
1.
> add deprecation warning to translated readmes

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
> Templates update

- .github/ISSUE_TEMPLATE/bug_report.md
Just fixing a typo in the issue template
> Update bug_report.md to fix typo and update version numbers

- scripts/helper_functions.sh
> replace doexit with shutdown

- README.md
- docker-compose.yml
- docusaurus/docs/getting-started/quick-setup.md
> add rest ports to examples

- Dockerfile
Update ARM64 image to resolve CVE issue
1.
> Update arm64 base image

- README.md
- docusaurus/docs/sponsors/sponsors.md
> Add indifferent broccoli (:|) sponsor

- README.md
- docusaurus/docs/getting-started/configuration/server-settings.md
- scripts/helper_functions.sh
- scripts/rest_api.sh
fix REST API a little. (docs, indent, return value)
My implementation was inadequate.
1. unzip [tests.zip](https://github.com/user-attachments/files/16023634/tests.zip)
2. cd tests/rest-cli
3. ./test-manualy.sh
```
palworld-server-docker/tests/rest-cli$ ./test-manualy.sh
[+] Building 1.7s (18/18) FINISHED                                                                       docker:default
=> [palworld internal] load build definition from Dockerfile                                                      0.1s
=> => transferring dockerfile: 7.14kB                                                                             0.0s
=> [palworld internal] load metadata for docker.io/library/golang:1.22.4-alpine                                   1.4s
=> [palworld internal] load metadata for …
```
> fix REST API a little. (docs, indent, return value)

- docusaurus/package-lock.json
> update npm packages for docusaurus

- Dockerfile
> Update multiple dependencies

- Dockerfile
> update arm base image

- .github/workflows/unit-test.yml
> add depotdownloader test

- docusaurus/docusaurus.config.js
- docusaurus/package-lock.json
- docusaurus/package.json
> add htmlLang, Canonical Base url and better sitemap.

- scripts/restore.sh
> fix linting errors

- docusaurus/package-lock.json
- docusaurus/package.json
> update docusaurus & dependancies
