thijsvanloef/palworld-server-docker

.gitattributes
Dockerfile
README.md
docker-compose.yml
scripts/start.sh

Being able to configure the admin password would be quite helpful
- Add `.gitattributes`, to ensure the scripts use LF line endings
- Add `ADMIN_PASSWORD` to the list of environment variables, which adds `--adminpassword` to the server arguments, this has been verified to work locally

Add ADMIN_PASSWORD environment variable

---

Dockerfile
README.md
docker-compose.yml
scripts/start.sh

fixes https://github.com/thijsvanloef/palworld-server-docker/issues/64
This PR solves the need to have an external RCON container to run RCON commands to the server. 
"Weird. This response is for another request." shows up when a command is run, but the command does get executed.
Issue already exists: https://github.com/itzg/rcon-cli/issues/28

Include RCON in docker image

---

Dockerfile
README.md
scripts/start.sh

This PR allows you to override the default query port (27015) with an environment variable

Changable Query Port

---

k8s/configmap.yaml
k8s/deployment.yaml
k8s/pvc.yaml
k8s/readme.md
k8s/secret.yaml
k8s/service.yaml

Just added support for kubernetes. We can use this as a starting point. I run it like this in my cluster and it works like a charm. Thx for the nice work @thijsvanloef

fix: added basic yamls for kubernetes support.

---

README.md
scripts/init.sh

* Add in graceful stop
* Using rcon was mentioned by @thijsvanloef in #62
* In the event rcon is not used then kill is used instead
1. Run with `RCON_ENABLED=true`
2. Join the game and move to a different location in game
3. Stop the container with ctrl + c
4. Restart container and join game again to verify it saved where you ended
5. Repeat 1 - 3 with `RCON_ENABLED=false` NOTE: this does not save without rcon

Graceful stop

---

README.md
chart/values.yaml
k8s/pvc.yaml

The steamcmd update requires an extra 2GB of free disk space. The container seems to be using around 8.7GB, which results in a steam update failure of `Error! App '2394010' state is 0x226 after update job.` since there isn't enough space to grab the new version in a 10GB disk. Bumping this to 12GB should result in ~3.4GB of free space, so there is a small buffer for future update size increases.
* Update documentation to help others who want to set up the container correctly to begin with.
1. N/A - documentation update only

Increase recommended disk size to 12GB.

---

README.md

* Fixed the link to go to docker-compose.yml within `README.md` being misplaced and going to the wrong place.
* Fixed `README.md`
1. 
* [v] I have performed a self-review of my code
* [v] I've added documentation about this change to the README.
* [v] I've not introduced breaking changes.

Fix: README.md docker-compose.yml link

---

README.md
migration/README.md
migration/migrate.sh

To solve #96 
I think `/palworld/Pal/Saved/Config/LinuxServer/GameUserSettings.ini` is generated after the service is started for the first time, so I can only write an additional script to facilitate migration.
After several experiments, the migration plan was determined to be successful.
This script is also tested.

Support migrate from an existing server

---

README.md

Added caveats for Boolean type environment variable options.
Added caveats for Boolean type environment variable options.
In fact, in my own experience, where case sensitivity prevented the option from being applied correctly, the cautionary note.
1. 
* [v] I have performed a self-review of my code
* [v] I've added documentation about this change to the README.
* [v] I've not introduced breaking changes.

Add: README.md Environment variable important statements

---

scripts/start.sh

Updating to using array for STARTCOMMAND due to issues that `su steam -c "${STARTCOMMAND}"` can have with escaped quotes and spaces, also this will allow for spaces in server names and passwords
Allow users to use spaces in environment variables
- Better handling of spaces in program arguments that should allow them, such as server name and passwords
1. Run the server with this change and have spaces in the passwords or in the server name
there is no mention spaces aren't supported, so this will just be helpful overall
fully tested this time instead of just testing printing the startcmd. sorry about that! here's proof:

Update start script

---

README.md
scripts/start.sh

* Removes the need to manually delete the PalWorldSettings.ini file if it is blank to trigger a copy of the default file at next startup.
* Using grep since that is already included in the image.
1. Start the container without `:/palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini`
2. Verify the file is created
3. Start the container with an empty (zero bytes, you can use touch) `:/palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini`
4. Verify the file is overwritten
5. Start container with a valid `:/palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini` (Ideally modify a value)
6. Verify the file not overwritten

Added fix for blank PalWorld Settings file

---

Dockerfile
scripts/init.sh
scripts/start.sh

* Replace  [itzg/rcon-cli](https://github.com/itzg/rcon-cli) with [gorcon/rcon-cli](https://github.com/gorcon/rcon-cli)
* Fix `Weird. This response is for another request.` error message.
* This rcon client works with multiple games, not just minecraft.
1. I created a separate container on my local machine.
2. I ran all of the main rcon commands.
gorcon/rcon-cli treats spaces as multiple commands.
So, `docker exec palworld-server rcon-cli shutdown 1` no longer works.
The solution is to enclose single commands with quotes.
`docker exec palworld-server rcon-cli "shutdown 1"`
This does not affect the interactive rcon-cli.

Change rcon-cli executable

---

k8s/configmap.yaml
k8s/deployment.yaml

For me, volume mount was not updating despite destroying the pod and spawning a new one.
Changing the hierarchy to be consistent with the data dir mount fixed this when redeploying despite k8s claiming the yaml was equivalent.
My goal was to implement changes to the tickrate. This exposes tickrate as a setting.
Resolved my issue. Server subjectively seems more active.
kubectl exec <pod name> -- cat /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini
Before: default contents despite configmap looking correct
After: reflects custom configmap with tickrate change
* [✅] I have performed a self-review of my code
* [✅] I've added documentation about this change to the README.
* [✅] I've not introduced breaking changes.

Make volume mount hierarchy consistent, implement tickrate

---

chart/templates/deployments.yaml
chart/values.yaml
k8s/deployment.yaml

It is relatively unsafe with the way Palworld handles it's server terminations to leave the default deployment setting of RollingUpdate. Switching to Recreate ensures the old pod is terminated and not writting to the volume while the new pod is starting.
Opionated change is done in the suggested deployment yaml and the chart sets Recreate by default but leave it a configurable option.
Deployed to my local cluster, valiadate that deployment still works and that it terminates the pod prior to scheduling the new pod.

modify deployment and chart for opionated deployment

---

README.md

* Many people attempt to edit `PalWorldSettings.ini` while the server is live and rebooting causing the changes to be overwritten. #29 #161 
*  This will explain you should only modify `PalWorldSettings.ini` while the server is off.
* Added to readme
1. Verify readme makes sense.
2. Start container and wait for server to start then stop it
3. Modify `PalWorldSettings.ini` 
4. Start container and wait for server to start
5. Verify `PalWorldSettings.ini` still has your changes
6. Modify `PalWorldSettings.ini` again
7. Stop the server
8. Verify the file is reverted

Updated readme to explain when the settings can be modified

---

Dockerfile
scripts/backup.sh
scripts/init.sh
scripts/start.sh

* Currently you start the container as root and during the start up process everything is ran as root except the command with `su`.
* Currently when backups are created they are created and owned by root however on next boot the permission is changed to steam:steam
* When starting with a PUID or PGID that is not 1000 you get the following error: `/tmp/dumps is not owned by us - delete and recreate`
```
palworld-server-test  | *****STARTING INSTALL/UPDATE*****
palworld-server-test  | tid(22) burning pthread_key_t == 0 so we never use it
palworld-server-test  | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
palworld-server-test  | Logging directory: '/home/steam/Steam/logs'
palworld-server-test  | /tmp/dumps is not owned by us - delete and recreate
palworld-server-test  | [  0%] …
```

Minimize Root Processes

---

chart/Chart.yaml
chart/VALUES_SUMMARY.md
chart/templates/deployments.yaml
chart/templates/services.yaml
chart/values.yaml

* Now deploying the healthz container and service port is optional;
* To avoid conflicts with multiples cloud providers and different load balancers provisioning/types
1. Git clone the repo;
2. Install Helm client and check if you have access to a Kubernetes cluster (tested on v1.29);
3. Create your values.override.yaml file and add the properties that are pertinent to your cluster;
4. Run the following command:
5. helm install --create-namespace --namespace palworld palworld chart/ --values values.override.yaml
6. The healthz container should not be created by default, the service should not have a 80/tcp port mapped

- Modified the chart, now the healthz container/service port is optional

---

.github/workflows/pages.yml
index.html

A helm repository, in GitHub pages
- Add a workflow to publish the `gh-pages` branch to GitHub pages on Push
- Add `index.html` which simply links to the helm repository `index.yaml` (When it gets created by a release)

Add initial GitHub pages 

---

README.md
docker-compose.yml
scripts/start.sh

* Fix incorrect environment variable handling
* In `PalWorldSettings.ini`, `ServerName`, `ServerDescription`, `AdminPassword`, `ServerPassword`, `PublicIP`, `Region`, and `BanListURL` should be enclosed in double quotes.
* Fix the incorrect handling of double quotes in `start.sh`.
1. Stop the Palworld server.
2. Build the container.
3. Delete `<mount_folder>/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini`.
4. Set a `SERVER_NAME` with spaces in the .env. e.g. SERVER_NAME="My Palworld Server"
5. Start the Palworld server.
6. Check the server name in the game.

Fix incorrect environment variable handling

---

artifacthub-repo.yml

Our helm chart should be good to go to put on artifact hub, https://artifacthub.io/
- Add `artifacthub-repo.yml` to `gh-pages`, which registers our helm chart to be picked up by artifact-hub

Add initial artifacthub-repo.yml

---

scripts/start.sh

* Add support macOS.
* `steamcmd` does not work properly on Docker in Apple Silicon environments, added two force tags(force platform type to linux and force platform bitness to 64) as it's just a command to download PalWorld dedicated server for a linux.
1. I built my own docker image with this changes and running private server on M1 Max Mac Studio with 32GB RAM.

add support macOS

---

docs/kr/README.md
docs/zh-CN/README.md
k8s/readme.md

Fix incorrect link and add zh_CN translations for kubernetes setup.

Fix incorrect link in zh-CN and kr README.md

---

charts/palworld/values.yaml

In a self-built cluster that does not support the Load Balancer feature, setting it to ClusterIP can prevent it from indefinitely getting stuck in 'pending' during creation.

Update serviceType to ClusterIP

---

README.md

* @Technetium1 for pointing out the misspelling
* Corrected readme
1. Verify it is indeed spelled correctly

Corrected Generat to Generator

---

README.md
scripts/backup.sh
scripts/init.sh
scripts/start.sh
scripts/update.sh

* Makes all booleans case insensitive
* No need to change what is being added into the INI files as it appears to be case insensitive in there too.
* Breaking a part #228 into smaller pieces.
Use random casing for the booleans and see if the changes are reflected in game.

Make booleans case insensitive

---

scripts/start.sh

Quotes allow for special characters to be used in the password field for the rcon config yaml.
* Allow or the use of special characters in rcon and admin passwords
* This is what yaml allows 
Tested with and without special characters.
1. Set env vars
2. Run EOL text insertion
3.  run `rcon-cli` to check errors

Add quotes to rcon.yaml password

---

charts/palworld/templates/deployments.yaml

Incorporate backup functionality before the termination of a container due to API requests or management events such as liveness/startup probe failure, preemption, resource contention, and others.
* Add backup before a container is terminated.
* Addressing https://github.com/thijsvanloef/palworld-server-docker/issues/243#issue-2110148331
* Refer to https://github.com/thijsvanloef/palworld-server-docker/pull/206#issue-2105868641
1. I haven't tested it yet. I'll conduct the test in a few days.

[Kubernetes] backup before a container is terminated

---

charts/palworld/templates/deployments.yaml

Sorry for my mistake. I forgot to save before testing, causing the inability to apply the Kubernetes deployment now. Created this PR to fix the issue.
Thanks to the person who raised this question. https://github.com/thijsvanloef/palworld-server-docker/pull/246#issuecomment-1924892511

fix k8s exec error

---

scripts/start.sh

*  Allow setting `ServerPassword` to an empty string through env `SERVER_PASSWORD`
* Resolve the issue of applying settings without manually modifying PalWorldSettings.ini when there is no server password.
* Addressing a similar issue as described in https://github.com/thijsvanloef/palworld-server-docker/issues/275#issue-2115930445.
1. Comment out the SERVER_PASSWORD or set it to an empty string.
2. Open the game and check if the `ServerPassword` in PalWorldSettings.ini is set to an empty string.

Fix: with no `SERVER_PASSWORD` can still apply setting

---

README.md
docs/kr/README.md

* Adjust the order of docker compose commands when backing up data with docker compose.
* If follow the previous commands leads to initialization issues on Ubuntu 22.04 LTS version (AWS EC2).
* Added missing Korean README translation
* need to stop first before changing something.
* [v] I have performed a self-review of my code
* [v ] I've added documentation about this change to the README.
* [v] I've not introduced breaking changes.

[FIX] fixed tips for docker compose & translations

---

README.md

* The README is out of date, and references an old ENV variable
* Updated the README
1. Follow the README to successfully use the Docker webhook integration

Update README.md to reference the new DISCORD_WEBHOOK_URL

---

docs/zh-CN/README.md

* Add `Sponsors`.
* Update `Environment variables`.
* Add  `Using Discord Webhooks`.

Update zh-cn read

---

Dockerfile.arm64

Fixing a bug where the scripts folder structure isnt copied exactly resulting in the files folder missing.

Fix folder copy on arm images

---

Dockerfile
scripts/compile-settings.sh
scripts/helper_functions.sh
scripts/start.sh

* #207 removed the error handling when creating the INI file
* Added exiting on error during compile settings
* Moved helper functions to their own script so they can be used in other scripts
1. Verify the container starts as normal
2. Remove the write permissions of the config file `chmod ugo-w palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini`
3. Start the container and verify you get this message `/palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini is not writable.` and `Unable to create /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini`
4. Delete the config file and remove write permission from the directory `rm -f palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini && chmod ugo-w palworld/Pal/Saved/Config/LinuxServer/`
5. Start the container and …

File checks for config generation

---

README.md

* Docker run example doesn't work because of the spaces in SERVER_NAME & SERVER_DESCRIPTION
* 
* Changed to quotes so spaces work
* Changed other values which can have spaces quotes
* Changed volume bind to match docker compose
1. Run the docker run examples
2. Verify the variables don't show quotes in the container

Fix docker run

---

README.md
docker-compose.yml

[Docker Documentation](https://docs.docker.com/compose/compose-file/05-services/#environment) doesn't support `var="value"` but rather:
* `var: "value"`
* `var: value`
* `var=value`
It is worth noting that you can do `"var=value"` but it's not mentioned
* People keep using quotes in array declaration of environmental variables. Changes array to map which docker compose supports the use of quotes
* Currently `- SERVER_NAME="World of Pals"` appears as `"World of Pals"`
* Currently `- SERVER_NAME=World of Pals` appears as `World of Pals`
* By switching to a map `SERVER_NAME: "World of Pals"` appears as `World of Pals`
*  `SERVER_NAME: World of Pals` appears as `World of Pals`
* Using maps also aligns our docker compose to be more align with k8s folder yamls as those tend to use maps (Ideally …

Changed array to map

---

Dockerfile

Docker Builds are failing as cm2network/steamcmd:root got updated, this should solve the package errors for the adm64,
@sonroyaalmerol Needs to update his image as well to fix the issues for arm
* 
1.

update package versions

---

README.md
docs/kr/README.md
docs/zh-CN/README.md
docusaurus/docs/getting-started/configuration/game-settings.md
docusaurus/docs/getting-started/configuration/server-settings.md
docusaurus/docs/getting-started/quick-setup.md
docusaurus/docs/guides/automatic-reboots.md
docusaurus/docs/guides/automatic-updates.md
docusaurus/docs/known-issues/known-issues.md

Improve docs to make it more easily accessible
* 
1.

improve docs

---

scripts/start.sh

* People have no way of knowing if their cron expressions are bad.
* Checking after each addition to the crontab since the test breaks on the first invalid expression
* Also makes it easier to understand which expression broke as I added  
1. Start the container and should see new section in output
```
palworld-server-test  | *****GENERATING CRONTAB*****
palworld-server-test  | BACKUP_ENABLED=true
palworld-server-test  | Adding cronjob for auto backups
palworld-server-test  | AUTO_UPDATE_ENABLED=true
palworld-server-test  | Adding cronjob for auto updating
palworld-server-test  | AUTO_REBOOT_ENABLED=true
palworld-server-test  | Adding cronjob for auto rebooting
palworld-server-test  | Cronjobs started
```
2. Start with all cron jobs disabled
```
palworld-server-test  | *****GENERATING …
```

Added exit on bad crontab

---

docusaurus/docs/help-translate/help-translate.md

Want to let people know that I am always looking for translators!
* 
1.

add translate guide

---

scripts/helper_functions.sh

* fixes that the server only sends messages with info level
1. Configure a Webhook in the environment variables
2. Start the server
3. Stop the server
4. Verify that there is sent a message with green and one with red

Fix Discord Webhook warn levels

---

scripts/helper_install.sh

With the recent addition of the option to pin the manifest this small bug made its way into the logs.
This change makes sure that the message only appears when needed
Added a check to make sure that the manifest is set before checking if it matches the current version
1. Do not set TARGET_MANIFEST_ID
2. start the server
3. notice that it only displays the message when applicable

Fix always showing: "Game not at target version"

---

Dockerfile

* Reduces image size
* Also delete /tmp/dumps to remove this error when starting as nonroot and a user which does not have a UID of 1000 `/tmp/dumps is not owned by us - delete and recreate`
Previously we changed the permission of `/home/steam/steamcmd/` which resulted in an image size increase of 300MB. Now making the directory we need and changing it's permission
1. Test that is runs with the default compose
2. Test as user 1000:1000
3. Test as any other user

Fixed image size

---

.github/workflows/release.yml
.github/workflows/security.yml
.gitignore

Add Security scanning that automatically uploads security advisories to github.
* 
Open PR, check that container scan runs

add trivy security scanning

---

.github/workflows/security.yml

* CodeQL Action v2 will be deprecated on December 5th, 2024. We currently get a warning in security because of this.
* Update now so we remove the warning instead of waiting till December 5th.
N/A

Change github/codeql-action/upload-sarif to v3

---

.github/workflows/linting.yml
.shellcheckrc
scripts/auto_reboot.sh
scripts/backup.sh
scripts/compile-settings.sh
scripts/discord.sh
scripts/helper_functions.sh
scripts/init.sh
scripts/restore.sh
scripts/start.sh
scripts/update.sh

* For all bash scripts which use `source` we must tell the linter to ignore it with `# shellcheck source=/dev/null`
* Added .shellcheckrc so we properly tell the linter the source of the file per [SC1091](https://github.com/koalaman/shellcheck/wiki/SC1091)
N/A

Add shellcheckrc

---

scripts/helper_functions.sh
scripts/helper_install.sh
scripts/start.sh
scripts/update.sh

* Code from #392 
* Only auto_update.sh and start.sh use the install functions no point in the others including them
1. Verify auto update and start still work.

Moved source includes

---

docs/zh-CN/README.md

Add: ZH-CN translations for locking game version

---

scripts/helper_functions.sh

The function broadcast command returns the result of rcon-cli. So a two minute reboot timer shows
```
palworld-server  | time="2024-02-21T17:33:00-05:00" level=info msg=starting iteration=0 job.command="bash /home/steam/server/auto_reboot.sh" job.position=0 job.schedule="33 17 * * *"
palworld-server  | time="2024-02-21T17:33:00-05:00" level=info msg="Broadcasted: The_Server_will_reboot_in_2_minutes" channel=stdout iteration=0 job.command="bash /home/steam/server/auto_reboot.sh" job.position=0 job.schedule="33 17 * * *"
palworld-server  | time="2024-02-21T17:34:00-05:00" level=info msg="Broadcasted: The_Server_will_reboot_in_1_minutes" channel=stdout iteration=0 job.command="bash /home/steam/server/auto_reboot.sh" job.position=0 job.schedule="33 17 * * *"
palworld-server  | …
```

Surpressing broadcast  output

---

Dockerfile

* Currently we do not check sha1sum for rcon but we do for supercronic
1. Test build
2. Change sha1sum and verify it stop building
```
=> ERROR [palworld rcon-cli_builder 3/3] RUN wget -q https://github.com/gorcon/rcon-cli/archive/refs/tags/v0.10.3.tar.gz -O rcon.tar.gz     && echo "33ee8077e66bea6ee097db4d9c923b5ed390d5  0.8s
------                                                                                                                                                                                             
> [palworld rcon-cli_builder 3/3] RUN wget -q https://github.com/gorcon/rcon-cli/archive/refs/tags/v0.10.3.tar.gz -O rcon.tar.gz     && echo "33ee8077e66bea6ee097db4d9c923b5ed390d584" rcon.tar.gz | sha1sum -c -     && tar -xzvf rcon.tar.gz     && rm rcon.tar.gz     && mv …
```

Add sha1sum check for rcon

---

scripts/restore.sh

* Resolves #437 
* Remove extra loop in restore
* Switching to pidof since we use pidof in start.sh
1. Verify restore still works

Switch to pidof in restore

---

scripts/player_logging.sh
scripts/start.sh

* Modify player logging to make more readable
* Switching to comm so we can see who have left or join instead of iterating to determine their change 
1. Start a server
2. Verify it logs it you leaving and joining in docker
3. With players in game test with others joining
4. Test multiple players joining within the same polling period
5. Delete player data, create a new players with any name that may break it (Spaces, commas, numbers, etc)

Player Logging Improvement

---

scripts/helper_install.sh

* Currently when the server check for updates it create a temporary file however the file is not deleted if there is an issue retrieving the manifest id.
* Removing file on failure
1. Create server
2. bash into the server and change the URL on line 63 in helper_install.sh to an invalid one
3. list files in `ls /tmp`
4. Run update
5. Verify there is no tmp file in `ls /tmp`

Remove temp file on failure in update required

---

Dockerfile
scripts/player_logging.sh

Fix `cli: execute: auth: rcon: dial tcp 127.0.0.1:25575: connect: connection refused` during startup
Poll the rcon port with netcat untill the rcon port is open and listening, after that start the player polling
Start the server, check if the `cli: execute: auth: rcon: dial tcp 127.0.0.1:25575: connect: connection refused` error stops showing but instead displaying: `Waiting for RCON port to open to show player logging...`

Fix RCON errors during startup

---

scripts/start.sh

Changes were made in 1.5.0 to server start args (lol why pocketpair?)
See https://tech.palworldgame.com/settings-and-operation/arguments/ for documentation
This PR updates the "EpicApp=PalServer" arg to the current "publiclobby" arg to relist community servers
Because Pocket Pair made us change it.
No testing needed, simple arg change per official documentation.

update "EpicApp=Palserver" to "-publiclobby" per 1.5.0 changes

---

README.md
docs/kr/README.md
docs/zh-CN/README.md
docusaurus/docs/getting-started/configuration/server-commands.md
docusaurus/i18n/de/docusaurus-plugin-content-docs/current/getting-started/configuration/server-commands.md
docusaurus/i18n/ko/docusaurus-plugin-content-docs/current/getting-started/configuration/server-commands.md
docusaurus/i18n/nl/docusaurus-plugin-content-docs/current/getting-started/configuration/server-commands.md
docusaurus/i18n/zh/docusaurus-plugin-content-docs/current/getting-started/configuration/server-commands.md

Old link redirected to a 404 page
Fix error in readme
....
Nothing to test

Fix link to rcon commands list

---

scripts/start.sh

Fix 485
The server stop messages was titled: "Start". Now correctly titled: "Stop"
* 
1.

fix bug that displays start when server has been stopped

---

scripts/backup.sh

Fix Discord old backup remove message to include old_backup_days.
Issue #501 that I drafted was modified by #502.
The message is now sent, but old_backup_days is broken.
So I fixed it.
To apply old_backup_message (e.g. 30).
1. I built my own image with the code changes and ran the `backup` command on it to see the messages sent to Discord.
Before fix
After fix

Fix Discord old backup remove message to include old_backup_days

---

.github/workflows/release.yml
Dockerfile
scripts/helper_functions.sh
scripts/helper_install.sh
scripts/start.sh

fix #493
Checks the container version against the latest released version. Helps with debugging and notifies users when a new version is available.
1.

Add Container version checking

---

scripts/backup.sh

This change means backup will no longer copy the games backup #520 
Simply using `--exclude backup` to exclude the backup folder as there are no other files or folders named backup in the Saved directory.
I had considered using find to so reduce the possibility of excluding the wrong files/directories if any were named backup however decided against this would be addressing an issue that the user must create.
1. Ideal up the game using the latest image
2. Backup again using the this PR
3. Verify this PR backup has no backup directory inside of it.
- [] I've added documentation about this change to the [docs](https://github.com/thijsvanloef/palworld-server-docker/tree/main/docusaurus/docs).

Excluding game backup folder in our backup.

---

Dockerfile
scripts/helper_functions.sh
scripts/player_logging.sh
scripts/start.sh

RCON cannot handle multibyte strings, so the ShowPlayers and Broadcast commands prefer to use the REST API when it is enabled.
Work around bug with multibyte strings in RCON.
The multibyte strings are now displayed correctly.
This is because it takes time to fix bugs in RCON.
1. create docker-compose.override.yml
```yaml
services:
palworld:
image: thijsvanloef/palworld-server-docker:debug
ports:
- 8212:8212/tcp  # add REST API port
environment:
REST_API_ENABLED: true
REST_API_PORT: 8212
SERVER_PASSWORD: "" # [override] no password for debug
```
2. build docker image for debug
```shell
docker build -t thijsvanloef/palworld-server-docker:debug .
```
3. run docker container
```shell
docker compose up
```
4. connect from client (PalWorld) and make new character with multibyte string name. …

The ShowPlayers and Broadcast commands prefer to use the REST API when it is enabled for player logging.

---

scripts/start.sh

1. Before registering Supercronic, check the size of the `crontab` file, not variables value.
2. If you perform the task registered in Supercronic, the log as like:
1. If you modify it this way, you don't need to modify it even if related functions are added.
2. Add the `-passthrough-logs` option to Supercronic so that the standard output of the file is displayed normally.
1. Set the `BACKUP_ENABLED` variable to `false` so that nothing is stored in the `crontab` file, and check whether the `else` part is executed.
2. Set the `BACKUP_ENABLED` or `AUTO_UPDATE_ENABLED` variable to `true` to see if it goes to the `if` part, and check the log on which `update` was executed.

Modifying Supercronic Related Code in start.sh

---

Dockerfile
README.md
docusaurus/docs/known-issues/known-issues.md
scripts/helper_functions.sh
scripts/rest_api.sh

Like rcon-cli, it supports a REST API command line interface.
Since rcon-cli is convenient, I also tried imitating rest-cli.
1. download test script.
[test-rest-cli.zip](https://github.com/thijsvanloef/palworld-server-docker/files/15074737/test-rest-cli.zip)
2. extract to project root.
```shell
unzip test-rest-cli.zip
chmod +x test-rest-cli.sh
```
4. build docker image with debug tag.
```shell
docker build -t thijsvanloef/palworld-server-docker:debug .
```
5. run test-rest-cli.sh and connect server from client manualy.
```
$ ./test-rest-cli.sh 
[+] Running 1/2
⠸ Network palworld-server-docker_default  Created
✔ Container palworld-server               Started 
wait healthy...... done.
TEST ... docker exec -i palworld-server rest-cli
OK
TEST ... docker exec -i palworld-server rest-cli -h
OK …
```

add REST API command line interface 'rest-cli'.

---

.github/workflows/unit-test.yml
Dockerfile

Supercronic has some security advisories, this will hopefully fix the issues.
1.

Update Supercronic to 0.2.30

---

.github/workflows/unit-test.yml
Dockerfile
scripts/start.sh

Fix ARM unit tests

---

Dockerfile

Bump supercronic to 0.2.31

---

Dockerfile

update supercronic to v0.2.32

---

scripts/restore.sh

Implements #521 
Only moving default palworld backups if the world exists in our backup/restore
1. Create a world which has game generated backups
2. Create a backup using our backup tool
3. Restore the backup
4. Verify the palworld backup folder exists in the restore

Updated restore.sh to move Palworld backup folder during restore

---

scripts/restore.sh

Implements #622 
Doing in order of newest first as I think it's more likely you want to restore a recent backup rather than an older one
1. Run restore and verify the order is newest to oldest
```
1) /palworld/backups/palworld-save-2024-11-17_07-52-20.tar.gz  4) /palworld/backups/palworld-save-2024-04-04_19-14-04.tar.gz
2) /palworld/backups/palworld-save-2024-04-05_00-00-00.tar.gz  5) /palworld/backups/palworld-save-2024-02-22_08-20-00.tar.gz
3) /palworld/backups/palworld-save-2024-04-04_19-15-20.tar.gz  6) /palworld/backups/palworld-save-2024-02-21_16-26-36.tar.gz
```

Changed restore order so newest is first

---

docusaurus/docs/getting-started/quick-setup.md

There's a typo in the docker run section of this page; if you attempt to run it, you'll get this error:
docker: invalid reference format: repository name (library/(Steam,Xbox,PS5,Mac)) must be lowercase.
Just replace the ":" with "=".
1. Run the docker run command in the command line of your server of choice

Fix Docker Run Typo
